image:
  repository: bitnamilegacy/spark
global:
  security:
    allowInsecureImages: true
master:
  configOptions:
    -Dspark.ui.reverseProxy=true
worker:
  configOptions:
    -Dspark.ui.reverseProxy=true
